title: Sopel
tagline: The Python IRC Bot
repo: https://github.com/sopel-irc/sopel
docs: /docs/

markdown: kramdown
highlighter: rouge

exclude:
  - LICENSE
  - README.md
  - UPDATING.md
  - Gemfile
  - Gemfile.lock
  - netlify-build.sh
  - runtime.txt
  - document_sopel_plugins.py
  - document_versions.py

include:
  - _headers
  - _redirects
  # Can't use docs/_static - see jekyll/jekyll#1352
  - _static

collections:
  tutorials:
    output: true
  usage:
    output: true
  upgrading:
    output: true
  appendices:
    output: true
  changelogs:
    output: true

defaults:
  - scope:
      path: "_usage"
    values:
      layout: article
      permalink: /usage/:name/
  - scope:
      path: "_upgrading"
    values:
      layout: default
      permalink: /usage/installing/upgrading-to-:name/
  - scope:
      path: "_appendices"
    values:
      layout: article
      permalink: /appendix/:name/
  - scope:
      path: "_changelogs"
    values:
      layout: changelog
      permalink: /changelog/:path/
  - scope:
      path: "_*/index.*"
    values:
      is_index: true
